language: node_js

node_js:
  - lts/*
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=d5c4115003e85ff60ac9a09342f3f7747db83b8c3ae4be0a52a8f33158db295d

before_script:
  - wget -O ./cctr https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  - chmod +x ./cctr
  - ./cctr before-build

after_script:
  - ./cctr after-build -t lcov --exit-code $TRAVIS_TEST_RESULT

jobs:
  include:
    - stage: deploy
      script: npm pack
      deploy:
        - provider: npm
          email: me@mgsisk.com
          api_key:
            secure: QmeavdXESqxKCL0tcjg7hK/gqvHje6DwPzx8lM6MIXhnLdJtEs+1Ikgc5b0nIrMt9ZnREwf9NTGlVMNcs/1k/XfL7NLwvfx0KLTQB06vYQ+nSaCzJrumJOOtNUV5jXvRwTUMBC60/zn9/TYnp3j2L+92QlKsDn6oRskOeZ5Kk/bM0cBLRCIqa3JTaYq7SlqHGpEvYJhEZM1hLRBUjF1MFJmPn3QXCFirFTz/0u0kAaS66YQLCHhRf8vd9kIbnhakK1mJHc/AyA2x7bgnSd4AY4Ns6sAr5xirqGctPR19bVKngBmFva/TItdl8RQg+b5qoy0XqZrKZFxlkWXhyjs0i130HvdqUf7zeEluBQWBPVDT0SwGH/sSnbkwnB6ntgOHFT5WQkp5vXolYlwWoiHoH+yMPe3aZUxrOKkHGcSLnbPyW8dfMTf50u3QpPOz2d2yprn3QmcYzZCwNxlvtLxcmD3i79LMgS2q7TcTza6pTdwqedU/uEqtSM/oKuxHo6AGD1H9+bwE1no2Z60r7BAYvH1nZZGpk0/w95zQM5UOgVayj3eKoLdUhwd84WRBn1CX5OmumNotQxbMv+mSFKesCsuGLFfMx6srnu3EWYNu/hP6bK1fDLTkkdkFOQSauAe+un1TwaCNyDZx1Xfgha7+wCruzM22VsunsIp28zhlIg0=
          on:
            repo: mgsisk/rollup-config
            tags: true
        - provider: npm
          registry: https://npm.pkg.github.com
          email: me@mgsisk.com
          api_key:
            secure: MqBsn9kYwcTyf0U4QBcydcPCdvBGjDegl11Tc5XPtz3g4TO9whNTlKH1sothvZbTjv3qLw+hwxIUI/2xbJQeCWpq/KgQOHdxaHeyVzIGZBhc+q8d464Y8BkWmFXMYWsPSz70+RqRZOwn4pn5DirKJTtQYFymd5mWmi6GZgKKiCXH7gCusIIAsVj4c87ywShPiE7F2VIv30dU+v+lNRnTs3KmN3ldt9MAt5flM1LYmG2FbHPfrn5MSsnGnrLiH3ceaUlGzM7VlIShOa4IfU5qvgCggsSfVedSFCAfvVRgrFx+K9EXFiNwqVY6FFPXzPMvHebbqv42azA794FKD3dqAesFicvjhHjealE8S1mJgz6s+uWlg0HhmIa43ATr4ZevzaYFL4gZuxaTQLUE0QBHySqXTT9LfnuKJg3vZJWg7PsteSrZCflHyIj6YVSrVmLasu/rOQ/3lEk1UIGGa7NGnxDS0vyz6rtJFkYuDfrSeHrt0c7z0NIA+D30PO0pETQZGczYUYtkUcnaTOAPlPrPQqPzgN5IZdDJsXVK+34mFtCC50a8cABGfGehMzHJvbNWvc2fSAF6c3hYApEd/CH6Envl9GyLiQagNeKtl2sAm8W6afJF2Hck2h12E1NkQC4pSeRTv9QIfcqXTR8v4MBvpNltVPUTlsAlp3I4ZXWaTUU=
          edge:
            branch: master
          on:
            repo: mgsisk/rollup-config
            tags: true
        - provider: releases
          skip_cleanup: true
          file_glob: true
          file: mgsisk-rollup-config-*.tgz
          api_key:
            secure: MqBsn9kYwcTyf0U4QBcydcPCdvBGjDegl11Tc5XPtz3g4TO9whNTlKH1sothvZbTjv3qLw+hwxIUI/2xbJQeCWpq/KgQOHdxaHeyVzIGZBhc+q8d464Y8BkWmFXMYWsPSz70+RqRZOwn4pn5DirKJTtQYFymd5mWmi6GZgKKiCXH7gCusIIAsVj4c87ywShPiE7F2VIv30dU+v+lNRnTs3KmN3ldt9MAt5flM1LYmG2FbHPfrn5MSsnGnrLiH3ceaUlGzM7VlIShOa4IfU5qvgCggsSfVedSFCAfvVRgrFx+K9EXFiNwqVY6FFPXzPMvHebbqv42azA794FKD3dqAesFicvjhHjealE8S1mJgz6s+uWlg0HhmIa43ATr4ZevzaYFL4gZuxaTQLUE0QBHySqXTT9LfnuKJg3vZJWg7PsteSrZCflHyIj6YVSrVmLasu/rOQ/3lEk1UIGGa7NGnxDS0vyz6rtJFkYuDfrSeHrt0c7z0NIA+D30PO0pETQZGczYUYtkUcnaTOAPlPrPQqPzgN5IZdDJsXVK+34mFtCC50a8cABGfGehMzHJvbNWvc2fSAF6c3hYApEd/CH6Envl9GyLiQagNeKtl2sAm8W6afJF2Hck2h12E1NkQC4pSeRTv9QIfcqXTR8v4MBvpNltVPUTlsAlp3I4ZXWaTUU=
          on:
            repo: mgsisk/rollup-config
            tags: true
